# Author: Max Stoddard
FROM node:20-bookworm-slim

WORKDIR /app

COPY dashboard/package.json dashboard/package-lock.json ./dashboard/
RUN cd dashboard && npm ci --include=dev

COPY dashboard ./dashboard
COPY input-data-versions ./input-data-versions

WORKDIR /app/dashboard

RUN npm run build:server

CMD ["npm", "run", "start:server"]
